### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by swervx** [Foereaper/Eluna-AIO-StoreSystem#2]
I don't understand why I have this error?
Thanks for your help
![Capture](https://user-images.githubusercontent.com/101983666/236097842-ae30df17-d183-4a68-953e-8df3c26388d3.PNG)

**Comment by qiuyunbest** [comment]
same error here

**Comment by Foereaper** [comment]
This error generally means you haven't installed the client assets properly.

**Comment by qidian008** [comment]
I am also having the same error

**Comment by qiuyunbest** [comment]
> 

that's right ! it's worked !

**Comment by 6yTblJIka** [comment]
same error

**Comment by 6yTblJIka** [comment]
> This error generally means you haven't installed the client assets properly.

installed according to instructions

help us xD)

**Comment by 6yTblJIka** [comment]
> I don't understand why I have this error? Thanks for your help ![Capture](https://user-images.githubusercontent.com/101983666/236097842-ae30df17-d183-4a68-953e-8df3c26388d3.PNG)

you need create patch-(4-9 or A-Z).mpq for game client

**Comment by qysjhythr** [comment]
you need to create a patch-*.MPQ ，and put your store_ui in this file with path /interface/Store_UI
and put this MPQ file into   your/game/client/data
