### ISSUE TITLE
Help [string "Store_Client.lua"]:30: attempt to index a nil value

### ISSUE THREAD

**Issue by Shorty5252** [Foereaper/Eluna-AIO-StoreSystem#4]
Hi, can you help me please? After the server starts and the player logs in, the message **[string "Store_Client.lua"]:30: attempt to index a nil value**. In Store_Client.lua at line 30 does not refer to nil. Can you help me please? The database is set correctly. Thanks

**Comment by Foereaper** [comment]
https://github.com/Foereaper/Eluna-AIO-StoreSystem/issues/2

Solution posted here
