### ISSUE TITLE
Question: Is there a way to reskin this button so that it matches the other ElvUI buttons?

### ISSUE THREAD

**Issue by Aldori15** [Foereaper/Eluna-AIO-StoreSystem#6]
Screenshot speaks for itself.  I use ElvUI as the UI overhaul and was wondering if you knew how to make it so that this button matches or inherits the ElvUI button properties?

![image](https://github.com/Foereaper/Eluna-AIO-StoreSystem/assets/15916673/5549b255-c79a-486a-a83c-8d5dbf3980eb)

**Comment by Foereaper** [comment]
https://github.com/Foereaper/Eluna-AIO-StoreSystem/blob/ea60eee3ed9f3d0cdbb04e432eca1472aef2249e/Server/Store_System/Store_Client.lua#L1189

You'd have to change this so the button has a proper identifier in the global namespace, then change elvUI to know that this button should be reskinned as well.

**Comment by Aldori15** [comment]
Not sure if I'm understanding.  So I've updated line 1189 by removing the local identifier and then changing nil to "StoreButton".
![image](https://github.com/Foereaper/Eluna-AIO-StoreSystem/assets/15916673/32a2c8eb-5408-4199-a40d-8ac9b694e3a7)

Then in Elvui I'm trying to use the identifier.  But the problem is when I try typing "StoreButton" on the Elvui one, it doesn't seem to recognize or try to populate it.  I assume i'm not referencing it properly?
![image](https://github.com/Foereaper/Eluna-AIO-StoreSystem/assets/15916673/8f91da41-6ba7-4e86-8b33-a605a79399c0)

**Comment by Foereaper** [comment]
It could be a call order issue, ie. the button not existing when ElvUI tries to reskin the buttons. Add a print in both functions and check which gets called first. I reckon ElvUI gets called first.

**Comment by Aldori15** [comment]
Added both print statements and ElvUI definitely gets called first.

![image](https://github.com/Foereaper/Eluna-AIO-StoreSystem/assets/15916673/bdf2ae35-23ae-499f-a15c-0b026e0fe2c2)

**Comment by Foereaper** [comment]
So yeah, the reskinning happens before the button even exists. You'll have to figure out how to call the re-skinning function then and call that after the store has been loaded.

**Comment by Aldori15** [comment]
Just need to adjust some minor formatting but was able to get it working.  Thanks for all of your help!  :)

![image](https://github.com/Foereaper/Eluna-AIO-StoreSystem/assets/15916673/bbfba63e-15cc-485b-b4dc-182df1adb008)
